// Generated by CIRCT unknown git version
module NOI(	// ../firrtl-examples/mlir/basicnoi.mlir:2:3
  input clock,	// ../firrtl-examples/mlir/basicnoi.mlir:2:21
        reset,	// ../firrtl-examples/mlir/basicnoi.mlir:2:45
        a,	// ../firrtl-examples/mlir/basicnoi.mlir:2:61
        b	// ../firrtl-examples/mlir/basicnoi.mlir:2:73
);

  reg hasBeenResetReg;	// ../firrtl-examples/mlir/basicnoi.mlir:8:10
  initial	// ../firrtl-examples/mlir/basicnoi.mlir:8:10
    hasBeenResetReg = 1'bx;	// ../firrtl-examples/mlir/basicnoi.mlir:8:10
  always @(posedge clock) begin	// ../firrtl-examples/mlir/basicnoi.mlir:8:10
    if (reset)	// ../firrtl-examples/mlir/basicnoi.mlir:8:10
      hasBeenResetReg <= 1'h1;	// ../firrtl-examples/mlir/basicnoi.mlir:3:13, :8:10
  end // always @(posedge)
  assert property (@(posedge clock)
                   disable iff (~(hasBeenResetReg === 1'h1 & reset === 1'h0)) a |=> b);	// ../firrtl-examples/mlir/basicnoi.mlir:3:13, :7:10, :8:10, :9:10, :10:10, :11:10, :12:5
endmodule
